name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod vendor

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD}}@e.coding.net/".insteadOf "git@e.coding.net:"
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
          cp script/core.yaml .core.yaml
          cp script/release.account.yaml .account.yaml
          cp script/release.moonlight.yaml .moonlight.yaml
          cp script/release.yaml .config.yaml
          cp script/zap.yaml .zap.yaml

      - name: Build
        run: make

#      - name: Test
#        run: go test -v .

